### ISSUE TITLE
skychart lat/lon wont update

### ISSUE THREAD

**Issue by sidt59** [Andosbor/project_number_one#45]
looks like there's a problem with the skychart. i was trying to see if it actually updates the view based on the zipcode you put in but it doesn't seem to work. 

here's what i know so far. when the url string is generated for the skychart iframe, it seems the values are coming up undefined. the location defaults to somewhere else. i'm not even certain the coordinates are in tx.

**Comment by sam-reinhard** [comment]
i looked into it and the coordinates on the chart seem to reflect the location of the user. I'm always seeing 30 north 97.7 west and that's pretty much right where I am

**Comment by sidt59** [comment]
ok so thats good. it could be gathering the location from the browser or it could be because we used austin to generate the iframe code itself. im looking into now too. if worse comes to worse i can pursue the http-server method and serve the source code in our scripts section

**Comment by desrogers** [comment]
It's fixed now...I think.

I made a new function using the Google Geocoding API to set the lat and lon variables based on the zip code. Now the zip code from the input field is passed into the `getLocation()` function, so the skychart updates and we don't have to figure out how to get a zip code into the embed

**Comment by sidt59** [comment]
hell yeah! right on man. I was in the process of figuring out node so we can send the source file over a secure server but i like your solution better :)

i'm closing this issue now that its resolved
